"""fix

Revision ID: 4705fd8337d0
Revises: 
Create Date: 2025-10-23 01:46:23.281480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4705fd8337d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_logs_log_type'), 'bot_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_bot_logs_telegram_id'), 'bot_logs', ['telegram_id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('conversation_history', sa.JSON(), nullable=False),
    sa.Column('collected_data', sa.JSON(), nullable=False),
    sa.Column('preferred_script', sa.String(length=10), nullable=False),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_telegram_id'), 'interview_sessions', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_interview_sessions_user_id'), 'interview_sessions', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('stocks', sa.JSON(), nullable=False),
    sa.Column('etfs', sa.JSON(), nullable=False),
    sa.Column('bonds', sa.JSON(), nullable=False),
    sa.Column('other', sa.JSON(), nullable=False),
    sa.Column('ai_model_used', sa.String(length=100), nullable=False),
    sa.Column('generation_time', sa.Float(), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_session_id'), 'recommendations', ['session_id'], unique=False)
    op.create_index(op.f('ix_recommendations_telegram_id'), 'recommendations', ['telegram_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=True),
    sa.Column('is_getcourse_client', sa.Boolean(), nullable=False),
    sa.Column('getcourse_email', sa.String(length=255), nullable=True),
    sa.Column('getcourse_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_script', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_interviews', sa.Integer(), nullable=False),
    sa.Column('completed_interviews', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_telegram_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_session_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_interview_sessions_user_id'), table_name='interview_sessions')
    op.drop_index(op.f('ix_interview_sessions_telegram_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_bot_logs_telegram_id'), table_name='bot_logs')
    op.drop_index(op.f('ix_bot_logs_log_type'), table_name='bot_logs')
    op.drop_table('bot_logs')
    # ### end Alembic commands ###
